--CREATE DATABASE "consultorio";
--
--DROP TABLE IF EXISTS "paciente";
--CREATE TABLE "paciente (VARCHAR 100 nome, VARCHAR 100 sobrenome, VARCHAR 100 rg, DATE dataDeCadastro, INT id)";
--
--DROP TABLE IF EXISTS "endereco";
--CREATE TABLE "endereco (VARCHAR 100 rua, INT id PRIMARY KEY NOT NULL AUTO_INCREMENT, INT numero, VARCHAR 100 cidade, VARCHAR 100 bairro)";
--
--CREATE TABLE